#!/bin/bash -ex
# executed after apply-overlay

echo "------------------------"
echo " Make SSL work properly "
echo "------------------------"
a2enmod ssl proxy_http headers rewrite
a2ensite phppgadmin
/etc/init.d/apache2 restart
