#!/bin/bash -ex
# executed before apply-overlay

ODOO_DIR=/opt/openerp/odoo

echo "--------------"
echo " Install Odoo "
echo "--------------"
git clone https://github.com/odoo/odoo.git $ODOO_DIR
chown -R openerp:openerp $ODOO_DIR
